@clubId=c8c7a7dc-0440-4391-83cf-f55fc9458b09

POST https://localhost:5443/api/v1/clubs/{{clubId}}/membership-options
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OTViYzk5NC1kOWRlLTQwNmYtOTkzYi0zMzgwYzMwMzg4YTQiLCJlbWFpbCI6ImhlbnJ5QGludGVybmV0LmNvbSIsImdpdmVuX25hbWUiOiJIZW5yeSIsImZhbWlseV9uYW1lIjoiOHRoIiwianRpIjoiM2U2NjU1OWItM2VjMS00MDRlLWEzOTUtNjFiMTVhMjRiM2IxIiwiZXhwIjoxNzEwNTc4Mzk2LCJpc3MiOiJxdWlja2NsdWJzIiwiYXVkIjoicXVpY2tjbHVicyJ9.iObaWFkXpyvkjcvQhxOjLusqRkafIR1OuBY7r_g6Evc
Content-Type: application/json

{
    "Name": "Annual Membership",
    "Period": "Yearly",
    "HasCutoff": true,
    "CutoffMonth": "12",
    "CutoffDay": "31",
    "Levels": [
        {
            "Name": "Adult",
            "Description": "",
            "MaxMembers": 1,
            "MinAge": 17,
            "MaxAge": null,
            "PriceAmount": 20.00
        },
        {
            "Name": "Junior",
            "Description": "",
            "MaxMembers": 1,
            "MinAge": null,
            "MaxAge": 17,
            "PriceAmount": 10.00
        },
        {
            "Name": "Family",
            "Description": "",
            "MaxMembers": 5,
            "MinAge": null,
            "MaxAge": null,
            "PriceAmount": 35.00
        }
    ]
}