@userId=727159A9-EC3B-4587-A083-D2000A7D8A52

PUT https://localhost:5443/api/v1/users/{{userId}}/set-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OTViYzk5NC1kOWRlLTQwNmYtOTkzYi0zMzgwYzMwMzg4YTQiLCJlbWFpbCI6ImhlbnJ5QGludGVybmV0LmNvbSIsImdpdmVuX25hbWUiOiJIZW5yeSIsImZhbWlseV9uYW1lIjoiOHRoIiwianRpIjoiMjJkYjVjMzQtZjZhNS00YzczLWFjZTUtODFkYTlhZDNiYjFmIiwiZXhwIjoxNzExNDQ5NDQyLCJpc3MiOiJxdWlja2NsdWJzIiwiYXVkIjoicXVpY2tjbHVicyJ9.qkb51AgTC8Pts3z6wSVeriIL5T2O_fl4oXyYvnfx17o

{
    "dateOfBirth": "1990-01-01",
    "building": "Buckingham Palace",
    "street": "The Mall",
    "locality": "",
    "town": "London",
    "county": "",
    "postcode": "SW1A 1AA"
}