POST https://localhost:5443/api/v1/clubs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlkZTViYi1iMDg3LTQwN2UtOWVmOC04ODZjYzFkMTc2MjEiLCJlbWFpbCI6ImhlbnJ5QGludGVybmV0LmNvbSIsImdpdmVuX25hbWUiOiJIZW5yeSIsImZhbWlseV9uYW1lIjoiOHRoIiwianRpIjoiODNkN2UzODktZTlkZS00ZmNhLWEwNzItODFiYzEzMjg2Y2NiIiwiZXhwIjoxNzA4OTI4NDY1LCJpc3MiOiJxdWlja2NsdWJzIiwiYXVkIjoicXVpY2tjbHVicyJ9.Dx8SiJZYRwO5iA1r-0oyWUU3AURjc-mgpAJMgdLEvwg

{
    "clubTypeCode": "MC",
    "fullName": "Tunbridge Wells motor Club",
    "acronym": "twmc",
    "website": "https://www.twmc.org.uk/"
}