POST https://localhost:5443/api/v1/memberships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OGE0Njc0MC1lYTU0LTQzZTAtOTRkNy0yOTgxMDYxNWZjNGMiLCJlbWFpbCI6ImhlbnJ5QGludGVybmV0LmNvbSIsImp0aSI6Ijc5NDRiZTdkLWI4ZTEtNGRiOC1hMzM0LTdiNjJhOTYyOGE5ZSIsImV4cCI6MTcwMTU2MzMwOCwiaXNzIjoicXVpY2tjbHVicyIsImF1ZCI6InF1aWNrY2x1YnMifQ.RNzsSmkODXksb5L7Modb597pk7s1BYNPomsjmdvuNGI

{
    "userId": "CCE1F99E-ABCD-4648-8C1D-2FE9DF20A68F",
    "additionalMembers": [],
    "membershipOptionId": "CDB0A19A-C382-4CCF-8452-8BF168DB2353",
    "membershipLevelId": "B95C08E7-B78C-4300-9633-53F9D0B2EC94"
}