POST https://localhost:41819/api/memberships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxM2NjMGY4NC01ZTdkLTQyM2MtOWYyOC05MGFkOGNhZThhMmMiLCJlbWFpbCI6InNvbWUub25lQGludGVybmV0LmNvbSIsImp0aSI6IjQ3Y2UwMjQwLTM1NDQtNDMxZi04NWQwLWU0NzczMTJjMjc0ZiIsImV4cCI6MTcwMDcwMzA4NSwiaXNzIjoicXVpY2tjbHVicyIsImF1ZCI6InF1aWNrY2x1YnMifQ.dOGGHJDHM_n8kkkXcMBBVwHYY4JBVHWtSra_FQ7Yb7c

{
    "userId": "9C4A231D-CF11-4439-982A-7952DF46D5A7",
    "additionalMembers": ["3FC2A7E0-B2EF-4060-A51A-1F15405795B4"],
    "membershipOptionId": "CDB0A19A-C382-4CCF-8452-8BF168DB2353",
    "membershipLevelId": "551CC6EE-CAD2-4F21-95A9-22CF75D75631"
}