POST https://localhost:5443/api/v1/memberships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OTViYzk5NC1kOWRlLTQwNmYtOTkzYi0zMzgwYzMwMzg4YTQiLCJlbWFpbCI6ImhlbnJ5QGludGVybmV0LmNvbSIsImdpdmVuX25hbWUiOiJIZW5yeSIsImZhbWlseV9uYW1lIjoiOHRoIiwianRpIjoiMjliY2Y0YTYtNTFlOC00ZGU4LWIzMjgtZmU1ZTAyOWRmZWJiIiwiZXhwIjoxNzExMzI2MTM5LCJpc3MiOiJxdWlja2NsdWJzIiwiYXVkIjoicXVpY2tjbHVicyJ9.lmnaZAt-XFWufMOGxcTQ1T8csSnUXxO2G_7TwoXivx4

{
    "userId": "995BC994-D9DE-406F-993B-3380C30388A4",
    "additionalMembers": ["727159A9-EC3B-4587-A083-D2000A7D8A52", "03EECEFC-F530-4B7D-93CC-F760817BF7F8"],
    "membershipOptionId": "18656917-cf50-44b7-ac65-4f9324e9428b",
    "membershipLevelId": "1a1d11c9-958d-4927-95c6-6fbe46bd7193"
}