GET https://localhost:5443/api/v1/memberships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OTViYzk5NC1kOWRlLTQwNmYtOTkzYi0zMzgwYzMwMzg4YTQiLCJlbWFpbCI6ImhlbnJ5QGludGVybmV0LmNvbSIsImdpdmVuX25hbWUiOiJIZW5yeSIsImZhbWlseV9uYW1lIjoiOHRoIiwianRpIjoiZTFiNGEyNzQtOWYxMi00OTRjLTlkNjMtZjhmN2I0MThmZGE2IiwiZXhwIjoxNzExMjI5NDI4LCJpc3MiOiJxdWlja2NsdWJzIiwiYXVkIjoicXVpY2tjbHVicyJ9.ka6r467JdXViwpQ_S9KmfP_20zNGEpdpoR9exSRIf9g

{
    "clubId": "C8C7A7DC-0440-4391-83CF-F55FC9458B09"
}