POST https://localhost:5443/api/v1/auth/register
Content-Type: application/json

{
    "email": "some.one@internet.com",
    "firstName": "Some",
    "lastName": "One",
    "password": "password123"
}