version: '3.4'

services:
  quickclubs.webapi:
    image: ${DOCKER_REGISTRY-}quickclubswebapi
    container_name: quickclubs.webapi
    build:
      context: .
      dockerfile: QuickClubs.WebApi/Dockerfile

  quickclubs.adminui:
    image: ${DOCKER_REGISTRY-}quickclubsadminui
    container_name: quickclubs.adminui
    build:
      context: .
      dockerfile: QuickClubs.AdminUI/QuickClubs.AdminUI/Dockerfile

  quickclubs.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quickclubs.db
    environment:
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/mssql/data
    volumes:
      - ../.containers/database:/var/opt/mssql/data
    ports:
      - 31433:1433

  quickclubs.smtp4dev:
    image: rnwood/smtp4dev:v3 # For docker-compose info, see https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml
    container_name: quickclubs.smtp4dev
    restart: always
    ports:
      - '3000:80' # port the smtp4dev web interface should be accessible on
      - '2525:25' # port the SMTP server should be accessible on (I dont think this needs to be externally accessible)
      #- '143:143' # port the IMAP server should be accessible on (I'm not using this - IMAP is used for retrieving messages, SMTP is for sending them)
    volumes:
        - ../.containers/smtp4dev-data:/smtp4dev
    environment:
      # See https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml
      - ServerOptions__HostName=smtp4dev

  quickclubs.dozzle:
    image: amir20/dozzle:latest
    container_name: quickclubs.dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:8080
